import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      >
        <header style={{backgroundColor: "grey", padding: "1rem"}}>
          Root Header
        </header>
        {children}
        <footer style={{backgroundColor: "grey", padding: "1rem"}}>
          Root Footer
        </footer>
      </body>
    </html>
  );
}
